#!/bin/bash
set -Eeuo pipefail

check_file()
{
    SUM1=$(md5sum "./checkpoints/checkalive.txt")
    sleep 300
    SUM2=$(md5sum "./checkpoints/checkalive.txt")
    if [ "$SUM1" == "$SUM2" ];
    then
        echo "$@: Crawler Have End, Restart"
        ./crawler.o 0 > output.txt &
    else
        echo "$@: Crawler Alive"
    fi
}

# ./crawler.o 0 >> output.txt &
# ./start0 > startlog.txt &
echo "$@: Start to run crawler first time"
while true; do
    check_file
done;
